CREATE DATABASE INLOCK_GAMES_MANHA;
GO

USE INLOCK_GAMES_MANHA;
GO

CREATE TABLE TIPOUSUARIO (
	idTipoUsuario SMALLINT PRIMARY KEY IDENTITY,
	tituloTipoUsuario VARCHAR(50) NOT NULL
);
GO

CREATE TABLE ESTUDIO (
	idEstudio SMALLINT PRIMARY KEY IDENTITY,
	nomeEstudio VARCHAR(50) NOT NULL
);
GO

CREATE TABLE JOGOS (
	idJogo SMALLINT PRIMARY KEY IDENTITY,
	idEstudio SMALLINT FOREIGN KEY REFERENCES ESTUDIO(idEstudio) NOT NULL,
	nomeJogo VARCHAR(50) NOT NULL,
	descricao VARCHAR(200) NOT NULL,
	dataLancamento DATE NOT NULL,
	valor DECIMAL NOT NULL
);
GO

CREATE TABLE USUARIO (
	idUsuario SMALLINT PRIMARY KEY IDENTITY,
	idTipoUsuario SMALLINT FOREIGN KEY REFERENCES TIPOUSUARIO(idTipoUsuario),
	email VARCHAR(50) NOT NULL,
	senha VARCHAR(50) NOT NULL
);
GO